type Dict = Record<string, string>;

const STRINGS: Record<string, Dict> = {
  en: {
    invalid_config: 'Invalid configuration',
    no_entity: 'No climate entity defined',
    detected: 'entities detected',
    advanced: 'Advanced / manual mapping',
    default_name: 'Ventilation',
    heat_recovery: 'Heat recovery',
    show_history: 'Show history',
    colder: 'colder',
    warmer: 'warmer',
    outside_air: 'Outside air',
    return_air: 'Return air',
    exhaust_air: 'Exhaust air',
    supply_air: 'Supply air',
    fan_off: 'Off',
    fan_low: 'Low',
    fan_medium: 'Medium',
    fan_high: 'High',
    chip_fan: 'Fan',
    chip_filter: 'Filter',
    chip_bypass: 'Bypass',
    chip_preheating: 'Preheating',
    chip_summer: 'Summer',
    chip_winter: 'Winter',
    state_off: 'Off',
    state_active: 'Active',
    filter_replace: 'Replace',
    filter_ok: 'OK',
    bypass_open: 'Open',
    bypass_closed: 'Closed',
    label_entity: 'CA350/550 climate entity (required)',
    label_animation: 'Animation',
    label_animation_speed_source: 'Speed source',
    label_animation_speed: 'Fixed speed (%)',
    label_color_scale: 'Color scale',
    label_temp_min: 'Fixed scale – min (°C)',
    label_temp_max: 'Fixed scale – max (°C)',
    label_show_legend: 'Show temperature scale',
    label_name: 'Name (optional)',
    label_tempSensor1: 'Outside air temperature',
    label_tempSensor2: 'Exhaust air temperature',
    label_tempSensor3: 'Return air temperature',
    label_tempSensor4: 'Supply air temperature',
    label_filterstatus: 'Filter status',
    label_bypass_valve: 'Bypass valve',
    label_summer_mode: 'Summer mode',
    label_preheat: 'Preheating',
    label_fan_speed_supply: 'Supply fan speed',
    label_fan_speed_exhaust: 'Exhaust fan speed',
    label_return_air_level: 'Return air level',
    label_supply_air_level: 'Supply air level',
    opt_animated: 'Animated (airflow + fans)',
    opt_static: 'Static',
    opt_speed_fixed: 'Fixed speed (%)',
    opt_speed_level: 'By air volume (supply/return %)',
    opt_scale_auto: 'Auto (current values)',
    opt_scale_fixed: 'Fixed (manual range)',
  },
  de: {
    invalid_config: 'Ungültige Konfiguration',
    no_entity: 'Keine climate-Entity ausgewählt',
    detected: 'Entities erkannt',
    advanced: 'Erweitert / manuelle Zuordnung',
    default_name: 'Wohnraumlüftung',
    heat_recovery: 'Rückgewinnung',
    show_history: 'Verlauf anzeigen',
    colder: 'kälter',
    warmer: 'wärmer',
    outside_air: 'Außenluft',
    return_air: 'Abluft',
    exhaust_air: 'Fortluft',
    supply_air: 'Zuluft',
    fan_off: 'Aus',
    fan_low: 'Stufe 1',
    fan_medium: 'Stufe 2',
    fan_high: 'Stufe 3',
    chip_fan: 'Lüfter',
    chip_filter: 'Filter',
    chip_bypass: 'Bypass',
    chip_preheating: 'Vorheizen',
    chip_summer: 'Sommer',
    chip_winter: 'Winter',
    state_off: 'Aus',
    state_active: 'Aktiv',
    filter_replace: 'Wechseln',
    filter_ok: 'OK',
    bypass_open: 'Offen',
    bypass_closed: 'Zu',
    label_entity: 'CA350/550 Climate-Entity (Pflicht)',
    label_animation: 'Animation',
    label_animation_speed_source: 'Tempo-Quelle',
    label_animation_speed: 'Festes Tempo (%)',
    label_color_scale: 'Farbskala',
    label_temp_min: 'Feste Skala – Min (°C)',
    label_temp_max: 'Feste Skala – Max (°C)',
    label_show_legend: 'Temperaturskala einblenden',
    label_name: 'Name (optional)',
    label_tempSensor1: 'Außentemperatur',
    label_tempSensor2: 'Fortlufttemperatur',
    label_tempSensor3: 'Rücklufttemperatur',
    label_tempSensor4: 'Zulufttemperatur',
    label_filterstatus: 'Filterstatus',
    label_bypass_valve: 'Bypass-Ventil',
    label_summer_mode: 'Sommermodus',
    label_preheat: 'Vorheizregister',
    label_fan_speed_supply: 'Lüfterdrehzahl Zuluft',
    label_fan_speed_exhaust: 'Lüfterdrehzahl Fortluft',
    label_return_air_level: 'Rückluft-Stufe',
    label_supply_air_level: 'Zuluft-Stufe',
    opt_animated: 'Animiert (Luftströme + Lüfter)',
    opt_static: 'Statisch',
    opt_speed_fixed: 'Festes Tempo (%)',
    opt_speed_level: 'Nach Luftmenge (Supply/Return %)',
    opt_scale_auto: 'Auto (aktuelle Werte)',
    opt_scale_fixed: 'Fest (manueller Bereich)',
  },
  nb: {
    invalid_config: 'Ikke gyldig konfigurasjon',
    no_entity: 'Ingen climate-enhet valgt',
    detected: 'enheter funnet',
    advanced: 'Avansert / manuell tilordning',
  },
};

export function localize(key: string, lang?: string): string {
  let code = (lang || 'en').replace(/['"]+/g, '').split('-')[0].toLowerCase();
  if (!STRINGS[code]) code = 'en';
  return STRINGS[code][key] ?? STRINGS.en[key] ?? key;
}

export function fanModeLabel(mode: string | undefined, lang?: string): string {
  const m = (mode ?? '').toLowerCase();
  const key = ({ off: 'fan_off', low: 'fan_low', medium: 'fan_medium', high: 'fan_high' } as Dict)[m];
  return key ? localize(key, lang) : (mode ?? '');
}
